 #+TITLE:uiina
#+AUTHOR: welkinSL
#+DATE: [2025-05-04 Sun]
* About
  This repository contains the python script =uiina.py=, modified from [[https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv][this script]] from [[https://github.com/mpv-player/mpv][mpv's repository at Github]].

  Last modified: [2025-05-04 Sun]

  #+begin_export html
<details>
<summary>Detailed explaination of the script</summary>
  #+end_export
** Modifications
   All mentions of =mpv= have been replaced with =IINA=
   In addition, differences such as IINA not quitting automatically after all files are played
   and the distinct method for passing options (consult =iina --help=) are noted.
** Single Instance Management
   This script ensures that only one instance of IINA is used.
   If invoked via the command line, it will attempt to append files to the playlist of an already running IINA instance
   but only if that instance was started with the =uiina= command.

   Any other IINA processes remain unaffected.
** Accepted Arguments
   The script accepts only filenames as arguments.
   No custom options are permitted

   Any additional arguments are interpreted solely as filenames.
** Playback Behavior
  When IINA is already running, the provided files are added to its internal playlist.

  If an argument does not correspond to an existing or playable file, IINA will simply bypass that entry without issue.
** Startup Characteristics
   If no appropriate instance of IINA is running, the script will launch IINA and assign control of the current terminal to it.
   To avoid cluttering logs (notably =~/.xsession-errors= or, on macOS, =stdout/stderr=), it deliberately suppresses output.
** Custom Configuration
   You may define a custom IINA binary path and options using the IINA environment variable.
   This variable is split on whitespace:
   + the first element specifies the IINA binary’s path
   + any subsequent items are options applied only when the script initiates IINA
     - If IINA is already running, these settings are ignored.

          #+begin_export html
</details>
  #+end_export
* How to install
** Using =brew= :: Recommended
   Tap =ed9w2in6/wsl= and install it:
   #+BEGIN_src sh
brew tap ed9w2in6/wsl
brew install uiina
   #+END_src
** From release :: Not recommended
   After downloading the =tgz= file,

   + Extract it.
   + Verify its checksum
   + Move the =uiina= folder to your desired location.
   + make a symbolic link of =uiina.py= in one of the directories
     under =$PATH=, it *must be named*: =uiina=
* Other notes
** Problem with =brew=
   Questions with =brew= will not be answered here. Go see
   [[https://github.com/ed9w2in6/homebrew-wsl][homebrew-wsl]] first.

   If it does not solve your problem, it is likely homebrew's problem.

   Always read [[https://docs.brew.sh/FAQ][homebrew's FAQ]], or [[https://github.com/Homebrew/discussions/discussions][its discussions]] to try to solve the problem yourself first.
   If there is an issue, go report it to [[https://github.com/Homebrew/homebrew-core/issues][homebrew-core]].

   Note that /homebrew/ *may not respond* to problem that is caused by a custom tap.
** Upstream Changes
   There seems to be updates upstream:
   https://github.com/mpv-player/mpv/commits/master/TOOLS/umpv

   I need to merge upstream changes (if applicable) since [2022-11-29 Tue]
