 #+TITLE:uiina
#+AUTHOR: welkinSL
#+DATE: [2025-05-04 Sun]
* About
** Origins
  This repository contains the python script =uiina.py=, modified from [[https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv][this script]] from [[https://github.com/mpv-player/mpv][mpv's repository at Github]].

  Last modified: [2025-05-04 Sun]

  #+begin_export html
<details>
<summary>Detailed explaination of the script</summary>
  #+end_export
** Differences with =umpv=
*** functions, variables, and CLI options renaming
    All mentions of =mpv= have been replaced with =iina= where applicable.

    It should be noted that IINA will NOT quite automatically after all files are played.
    The way =mpv= options are via =iina= is also different:

           #+begin_src sh :results output scalar :eval yes
iina --help | head -n 10
    #+end_src

#+RESULTS:
#+begin_example
Usage: iina-cli [arguments] [files] [-- mpv_option [...]]

Arguments:
--mpv-*:
        All mpv options are supported here, except those starting with "--no-".
        Example: --mpv-volume=20 --mpv-resume-playback=no
--separate-windows | -w:
        Open all files in separate windows.
--stdin, --no-stdin:
        You may also pipe to stdin directly. Sometimes iina-cli can detect whether
#+end_example

*** keep-alive when new socket for auto cleanup on quit
    Since [[https://github.com/mpv-player/mpv/commit/dfbd60f9bb847abc564db477c32df124324959ad][commit dfbd60f]] =umpv= had changed to NOT wait for quit even for
    new socket / pipe.

    However, due to =uiina='s auto cleanup feature we DO need it to keep alive
    and clean up on quit.
*** read from stdin and using URL
    unlike =mpv= we allow reading from stdin.
    We also accepts URLs too due to IINA's builtin =yt-dlp=.
*** socket directory
    You can configure the socket directory with a environment variable.

    These are accepted, in order of precedence:
    + =UIINA_SOCKET_DIR=
    + =XDG_RUNTIME_DIR=
    + =HOME=
      - in =uiina= we take this from =Path.home()=, unlike =umpv= which relies on env var.
    + =TMPDIR=
** Shared features
*** Single instance
    This script ensures that only one instance of IINA is used.

    If invoked via the command line, it will attempt to append files to the playlist of an already running IINA instance
    but only if that instance was started with the =uiina= command, which can be detected by socket / pipe existence.
    Any other IINA processes remain unaffected.

    If an target argument is invalid, IINA will quit with a non-zero exit code.

    If no good IINA running, that is no socket / pipe file, they will be created and a fresh IINA instance will be launch.
    To avoid cluttering logs (notably =~/.xsession-errors= or, on macOS, =stdout/stderr=), it deliberately suppresses output.
*** Custom Configuration
    You may define a custom IINA (originally =MPV= for =umpv=) binary path and options using some appropriate environment variable.

    This variable is split on whitespace:
    + the first element specifies the IINA binary’s path
    + any subsequent items are options applied only when the script initiates IINA
      - If IINA is already running, these settings are ignored

           #+begin_export html
 </details>
   #+end_export
* How to install
** Using =brew= :: Recommended
   Tap =ed9w2in6/wsl= and install it:
   #+BEGIN_src sh
brew tap ed9w2in6/wsl
brew install uiina
   #+END_src
** From release :: Not recommended
   After downloading the =tgz= file,

   + Extract it.
   + Verify its checksum
   + Move the =uiina= folder to your desired location.
   + make a symbolic link of =uiina.py= in one of the directories
     under =$PATH=, it *must be named*: =uiina=
* Other notes
** Problem with =brew=
   Questions with =brew= will not be answered here. Go see
   [[https://github.com/ed9w2in6/homebrew-wsl][homebrew-wsl]] first.

   If it does not solve your problem, it is likely homebrew's problem.

   Always read [[https://docs.brew.sh/FAQ][homebrew's FAQ]], or [[https://github.com/Homebrew/discussions/discussions][its discussions]] to try to solve the problem yourself first.
   If there is an issue, go report it to [[https://github.com/Homebrew/homebrew-core/issues][homebrew-core]].

   Note that /homebrew/ *may not respond* to problem that is caused by a custom tap.
** DONE Upstream Changes
   :LOGBOOK:
   - State "DONE"       from              [2025-05-04 Sun 18:47]
   :END:
   Merged at [2025-05-04 Sun]

   There seems to be updates upstream:
   https://github.com/mpv-player/mpv/commits/master/TOOLS/umpv

   I need to merge upstream changes (if applicable) since [2022-11-29 Tue]
